{
 "title": "CT-COVID",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Response Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(fastapi_http_request_duration_seconds_sum{handler=~\"/|/docs|/models|/predict\",job=\"ct-covid\"}[5m])"
    }
   ]
  },
  {
   "title": "Prediction Output",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_model_output_bucket{job=\"ct-covid\",le=~\"0\\\\.0|1\\\\.0|2\\\\.0\"}"
    }
   ]
  },
  {
   "title": "Received Data",
   "type": "graph",
   "description": "Sum of request sizes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fastapi_http_request_size_bytes_sum{handler=~\"/predict\"}[5m])"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "bargauge",
   "description": "displays the total number of request per endpoint",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_http_requests_total{handler=~\"/|/docs|/models|/predict\"}"
    }
   ]
  }
 ]
}