# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: checkout@v2
      with:
        fetch-depth: ‘2’
    - name: DVC pull
      run: |
        pip install -r requirements.txt
        pip install dvc[gdrive]
        dvc pull models/
    - name: Generate Report
      run: |
        pip install pytest pytest-cov 
        pytest --cov src/covidx tests/ -m "not gpu"
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
