name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:  
    - name: Setup Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: '3.9'
    - name: DVC pull
      run: |
        pip install -r requirements.txt
        pip install dvc[gdrive]
        dvc pull models/
    - name: Generate Report
      run: |
        pip install pytest pytest-cov 
        pytest --cov src/covidx tests/ -m "not gpu"
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v
